set nocompatible
filetype plugin on 
set hidden

syntax on

" for command-t
let mapleader = ","

noremap \ ,
set cursorline

" search highlighting
set hls is
set incsearch
nnoremap <silent> <C-l> :nohl<CR><C-l>
nmap ,c :%s///gn<CR>

" no tabs, but 2 spaces as indenting
set tabstop=2
set expandtab
set shiftwidth=2
set shiftround

" no arrow keys allowed
noremap <Up> <Nop> 
noremap <Down> <Nop> 
noremap <Left> <Nop> 
noremap <Right> <Nop>

" extend * search on visual selection
" from practical vim ch13 (last tip)
xnoremap * :<C-u>call <SID>VSetSearch()<CR>/<C-R>=@/<CR><CR> 
xnoremap # :<C-u>call <SID>VSetSearch()<CR>?<C-R>=@/<CR><CR>

function! s:VSetSearch()
  let temp = @s
  norm! gv"sy
  let @/ = '\V' . substitute(escape(@s, '/\'), '\n', '\\n', 'g') 
  let @s = temp
endfunction

" Tell vim to remember certain things when we exit
"  '10  :  marks will be remembered for up to 10 previously edited files
"  "100 :  will save up to 100 lines for each register
"  :20  :  up to 20 lines of command-line history will be remembered
"  %    :  saves and restores the buffer list
"  n... :  where to save the viminfo files
set viminfo='10,\"100,:20,%,n~/.viminfo

function! ResCur()
  if line("'\"") <= line("$")
    normal! g`"
    return 1
  endif
endfunction

augroup resCur
  autocmd!
  autocmd BufWinEnter * call ResCur()
augroup END
